services:
  gk-traefik:
    image: traefik:v2.10
    container_name: gk-traefik
    restart: unless-stopped
    ports:
      - "80:80" # HTTP
      - "443:443" # HTTPS
      - "8080:8080" # Traefik Dashboard
    networks:
      - kafka_network
    command:
      - --log=true
      - --log.level=ERR
      - --tracing=false
      - --accesslog=true
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dashboard.rule=Host(`monitor.localhost`)"
      - "traefik.http.routers.dashboard.entrypoints=websecure"
      - "traefik.http.routers.dashboard.tls=true"
      - "traefik.http.routers.dashboard.service=api@internal"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./.docker/traefik/traefik.toml:/traefik.toml
      - ./.docker/traefik/cert.pem:/certs/cert.pem
      - ./.docker/traefik/key.pem:/certs/key.pem

  zookeeper:
    image: bitnami/zookeeper:3.8.1
    container_name: gk-zookeeper
    networks:
      - kafka_network
    environment:
      ALLOW_ANONYMOUS_LOGIN: 'yes'
      ZOO_MAX_CNXNS: 60

  kafka:
    image: bitnami/kafka:3.5.0
    deploy:
      replicas: 3
    networks:
      - kafka_network
    environment:
      ALLOW_PLAINTEXT_LISTENER: 'yes'
      KAFKA_CFG_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CFG_NUM_PARTITIONS: 4
      KAFKA_CFG_PROCESS_ROLES: "broker"
    restart: on-failure
    depends_on:
      - zookeeper

  kafka-init:
    image: bitnami/kafka:3.5.0
    container_name: gk-kafka-init
    networks:
      - kafka_network
    command: [ "/bin/bash", "-c", "/topics.sh" ]
    environment:
      KAFKA_CFG_ZOOKEEPER_CONNECT: zookeeper:2181
    depends_on:
      kafka:
        condition: service_started
    volumes:
      - type: bind
        source: ./topics.sh
        target: /topics.sh
      - type: bind
        source: ./topics.txt
        target: /topics.txt
    init: true

  kafdrop:
    image: obsidiandynamics/kafdrop:3.27.0
    container_name: gk-kafdrop
    environment:
      KAFKA_BROKERCONNECT: kafka:9092
      JVM_OPTS: -Xms32M -Xmx64M
      SERVER_SERVLET_CONTEXTPATH: /
    networks:
      - kafka_network
    labels:
      - traefik.enable=true
      - traefik.http.routers.kafdrop.rule=Host(`kafdrop.localhost`)
      - traefik.http.routers.kafdrop.entrypoints=websecure
    depends_on:
      - kafka
  relay:
    build:
      context: ../gk-kafka-relay
      dockerfile: Dockerfile
    container_name: gk-kafka-relay
    volumes:
      - .:/relay
    labels:
      - traefik.enable=true
      - traefik.http.routers.relay.rule=Host(`relay.localhost`)
      - traefik.http.routers.relay.entrypoints=websecure
      - traefik.http.services.relay.loadbalancer.server.port=8099
    networks:
      - kafka_network
  client:
    build:
      context: ../gk-kafka-client
      dockerfile: Dockerfile
    container_name: gk-kafka-client
    ports:
      - "3000:3000"
    volumes:
      - ../gk-kafka-client:/app
      - ../gk-kafka-client/certs:/app/certs
    working_dir: /app
    networks:
      - kafka_network
  auth:
    build:
      context: ../golang-kafka-hybrid-auth
      dockerfile: Dockerfile
    container_name: gk-kafka-auth
    volumes:
      - ../golang-kafka-auth:/app
    working_dir: /app
    labels:
      - traefik.enable=true
      - traefik.http.routers.auth.rule=Host(`auth.localhost`)
      - traefik.http.routers.auth.entrypoints=websecure
      - traefik.http.services.auth.loadbalancer.server.port=3000
    networks:
      - kafka_network
networks:
  kafka_network:
    name: kafka_test_network
