[api]
dashboard = true
insecure = true

[entryPoints]
  [entryPoints.web]
    address = ":80"
    [entryPoints.web.http.redirections.entryPoint]
      to = "websecure"
      scheme = "https"

  [entryPoints.websecure]
    address = ":443"

[certificatesResolvers.default]
  [certificatesResolvers.default.static]
    [certificatesResolvers.default.static.certificates]
      certFile = "/certs/cert.pem"
      keyFile = "/certs/key.pem"

#[tracing]
#  servicename = "tracing"
#   [tracing.jaeger]
#     samplingParam = 1.0
#     samplingServerURL = "http://jaeger:5778/sampling"
#     samplingType = "const"
#     localAgentHostPort = "jaeger:6831"

[providers.docker]
endpoint = "unix:///var/run/docker.sock"
watch = true
exposedbydefault = false
